---
- hosts: balancer
  become: yes

  vars:
    firewall_allowed_tcp_ports:
      - "22"
      - "80"
    haproxy_backend_servers:
      - name: 192.168.4.3
        address: 192.168.4.3:80
      - name: 192.168.4.4
        address: 192.168.4.4:80

  roles:
    - geerlingguy.firewall
    - geerlingguy.haproxy

- hosts: app
  become: yes

  vars:
    firewall_allowed_tcp_ports:
      - "22"
      - "80"

  roles:
    - geerlingguy.firewall
    - geerlingguy.apache
