---
- hosts: all
  become: true
  tasks: 
  - name: Install Apache
    command: yum install --quiet -y httpd httpd-devel
  - name: Copy configuration files
    command: >
      cp httpd.conf /etc/httpd/conf/httpd.conf
  - command: >
      cp httpd-vhost.conf /etc/httpd/conf/httpd-vhost.conf
  - name: Start Apache and configure it to run at boot.
    command: service httpd start
  - command: chkconfig httpd on

