
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "geerlingguy/ubuntu1604"
  config.vm.network "private_network", ip: "192.168.66.66"
  config.vm.hostname = "solr-app.test"
  config.ssh.insert_key = false

  config.vm.provider :VirtualBox do |v|
    v.memory = 2024
  end

  # Ansible provisioner.
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end
end